### ISSUE TITLE
Sorting on association doesn't work for me

### ISSUE THREAD

**Issue by kibaekr** [dadooda/handles_sortable_columns#11]
I saw the closed issue that another user submitted, and I tried doing something similar, but it doesn't work for me.

Course belongs_to category 
Category has_many courses

```
  #View
 <%= sortable_column "Category", column: "category_title" %>


##Courses Controller
 def index
     order = sortable_column_order do |column, direction|
       case column
       when "category_title"
         "category.title #{direction}" 
       end
     end
     if params[:query].blank? 
       @courses = current_account.courses.order(order).paginate(:page => params[:page], :per_page => 15)
     else 
       @courses = current_account.courses.search_by_content(params[:query]).order(order).paginate(:page => params[:page], :per_page => 15)
     end
   end
```

Error message: 

PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "categories"
LINE 1: ...urses"  WHERE "courses"."account_id" = 2 ORDER BY categories...
                                                             ^
: SELECT  "courses".\* FROM "courses"  WHERE "courses"."account_id" = 2 ORDER BY categories.title asc LIMIT 15 OFFSET 0
# 

Also, how would I be able to use the methods I defined in my models? 
i.e. test.average_score  
=> average_score is not saved in a table but is calculuted in the test.rb model

**Comment by dadooda** [comment]
Keith,

The issues you are referring to are not really related to `handles_sortable_columns`. The gem is only responsible for assigning `column` and `direction` based on HTTP request parameters.

In your examples there's clearly not enough tables in the query set so it's no wonder in some circumstances `categories.titles` is not available because the table is not there. Consider using a join perhaps (SQL `JOIN`, Arel `joins()`).

> Also, how would I be able to use the methods I defined in my models?  i.e. test.average_score.

There is no straightforward way to do it, and, again, it's out of the gem's scope. But, in general sense, to sort by a non-column expression you should have this expression computed per each row **on SQL server end**. Something like `SELECT *,SOME_FUNC(table.a, table.b, ...) AS average_score`. Then, some SQL servers will allow you to include `average_score` in a `WHERE` conditions. Some will make you use `HAVING`.

If you are not yet familiar with expressions like this, I'd recommend you to play with it for a while in SQL console. Just write some queries, making closer to what you eventually need at every step. Please don't expect Arel to keep you "SQL-clean", since for more or less complex queries you will have to use fragments of SQL, there's no workaround for that.
