### ISSUE TITLE
Sortable column for referenced name in other table

### ISSUE THREAD

**Issue by kakubei** [dadooda/handles_sortable_columns#7]
Thanks for a simple and functional plugin. But I have a question:

I have a column that is a lookup of the name of a column in another table. 

That is, I have cities.country_id as a column and in the View template I do:

`city.country.name` to display the name. 

I would like to be able to sort by this column, but the countries.name, not the cities.country_id. 

Is this possible with the plugin? If so how? 

Thanks.

**Comment by dadooda** [comment]
> I would like to be able to sort by this column, but the countries.name, not the cities.country_id.
> Is this possible with the plugin? If so how?

Sure thing! Just use the mnemonic column name which you then "catch" via the block form of `sortable_column_order`, like this:

```
<%= sortable_column "Country", :column => "country_name" %>
...
order = sortable_column_order do |column, direction|
  case column
  ...
  when "country_name"
    "countries.name #{direction}"
  ...
  end
end
```

You don't have to export **real** database column names into the view. In fact, arguments to `sortable_column` are just anything. In the example above I've created the ficticious column called `country_name`. It maps to `countries.name` or whatever, this is handled by the controller.

Hope that was useful.

**Comment by kakubei** [comment]
Thanks for the quick reply. The problem is that if I do it this way I get a Mysql error because the countries.name column is unknown for the City controller. In the City controller I have this:

```
@cities = City.order(order).page(params[:page])
```

And of course, it knows nothing of the countries columns. I think I'll need to do a join for it to recognize the column, but was hoping to avoid that.

**Comment by dadooda** [comment]
Of course you need a join.

By the way, if you only use the joined `countries` table just for
sorting, you can join it conditionally. Something like:

```
scope = City.scoped

...

order = sortable_column_order do |column, direction|
  case column
  ...
  when "country_name"
    scope = scope.joins(:country)
    "countries.name #{direction}, ..."
  ...
  end
end

@records = scope.order(order)
```

----- Original Message -----
From: kakubei reply@reply.github.com
To: Alex Fortuna alex.r@askit.org
CC: 
Time: Wed, 27 Jun 2012 11:01:25 -0700
Subject: [handles_sortable_columns] Sortable column for referenced name in other table (#7)
Attachments: <none>

Thanks for the quick reply. The problem is that if I do it this way I get a Mysql error because the countries.name column is unknown for the City controller. In the City controller I have this:

```
@cities = City.order(order).page(params[:page])
```

And of course, it knows nothing of the countries columns. I think I'll need to do a join for it to recognize the column, but was hoping to avoid that.

---

**Comment by kakubei** [comment]
Thanks a lot for all your help, this is good stuff!
